export const DIVISI_LIST = [
  "CUS - CORPORATE SECRETARY", "CUL - GRC AND LEGAL", "CUG - LOGISTIC",
  "CUI - INTERNAL AUDIT", "CUP - STRATEGIC PLANNING", "COS - HSE AND SECURITY",
  "COC - COMMERCIAL", "COH - TRAIN SERVICES FACILITIES AND CUSTOMER CARE",
  "COLA - LOCAL TRAIN", "COLB - AREA II BANDUNG", "COLS - AREA VIII SURABAYA",
  "CTI - INFORMATION TECHNOLOGY", "CTP - MAINTENANCE PLANNING AND EVALUATING",
  "CTR - ROLLING STOCK", "CTS - INFRASTRUCTURE", "COCB - BASOETTA DEPARTMENT",
  "CARM - RISK MANAGEMENT", "CUT - TESTING COMMITEE", "CAF - FINANCE",
  "CAA - BUDGETING AND ACCOUNTING", "CAH - HUMAN CAPITAL", "CAP - PSO AND TAC",
] as const;

export const DIVISI_OPTIONS = DIVISI_LIST.map((divisi) => ({ value: divisi, label: divisi }));
